[project]
name = "example-pytest-selfie"
version = "0.1.0"
description = "An example project for using the pytest plugin for selfie snapshot testing."
authors = [
    "Selina Delgado <sdelgado411@gmail.com>",
    "Harvir Sahota <hsahota2312@gmail.com>",
    "Ned Twigg <ned.twigg@diffplug.com>",
    "Edwin Ye <EdwinYeDeveloper@gmail.com>"
]
license = "Apache-2.0"
requires-python = ">=3.9"

[project.dependencies]
selfie-lib = { path = "../selfie-lib", develop = true }
pytest-selfie = { path = "../pytest-selfie", develop = true }

[tool.ruff]
lint.extend-select = ["I"]
