on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'csharp/**'
defaults:
  run:
    working-directory: csharp
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        jre: [11]
        os: [ubuntu-latest, windows-latest]
        dotnet-version: ['6.0.x']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
      - run: dotnet build
