import clsx from "clsx";
export const buttonClasses = clsx([
  "flex",
  "justify-center",
  "items-center",
  "border",
  "border-black",
  "cursor-pointer",
  "border-2",
  "wide-phone:border-[4px]",
  "p-1",
  "wide-phone:h-[53px]",
  "rounded-[12px]",
  "wide-phone:rounded-[16px]",
  "text-sm",
  "wide-phone:text-lg",
  "hover:text-white",
  "hover:bg-blue",
  "text-black",
  "bg-white",
  "shadow-button",
  "tablet:shadow-button-tablet",
]);
